# k8s/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: online-library-service
  namespace: online-library
spec:
  selector:
    app: online-library
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
  type: LoadBalancer  # or NodePort if using Minikube/Docker Desktop
